window.GameUI = (() => {
  const U=GameUtils;
  const screen=()=>document.getElementById('screen');
  const clubLogo=(club,sizeClass='fixture-logo')=>`<div class="${sizeClass}" style="background:linear-gradient(135deg,${club.colors[0]},${club.colors[1]});color:${club.colors[1]};border:1px solid rgba(255,255,255,.18)">${U.escapeHTML(club.short)}</div>`;
  function set(html){screen().innerHTML=html;window.scrollTo(0,0)}
  function toast(msg){const layer=document.getElementById('toast-layer'),el=document.createElement('div');el.className='toast';el.textContent=msg;layer.appendChild(el);setTimeout(()=>el.remove(),2200)}
  function openModal({title,body,footer='',closable=true}){
    const layer=document.getElementById('modal-layer');layer.classList.add('open');layer.setAttribute('aria-hidden','false');
    layer.innerHTML=`<div class="modal"><div class="modal-head"><strong>${U.escapeHTML(title)}</strong>${closable?'<button class="icon-btn" data-action="close-modal">✕</button>':''}</div><div class="modal-body">${body}</div>${footer?`<div class="modal-foot">${footer}</div>`:''}</div>`;
  }
  function closeModal(){const l=document.getElementById('modal-layer');l.classList.remove('open');l.setAttribute('aria-hidden','true');l.innerHTML=''}
  function renderMenu(){
    const slots=SaveSystem.list();
    set(`<section class="screen menu-screen">
      <div class="card brand-panel">
        <div><div class="brand-mark">⚽</div></div>
        <div><div class="card-title accent">PLAYER CAREER SIMULATION</div><h1>CAREER<br>STORY</h1><p class="slogan">YOU CREATE THE PLAYER.<br>THE GAME CREATES THE STORY.</p></div>
        <div><button class="btn btn-primary" data-action="new-career">＋ New Career</button><div class="version">First Playable Build · Save format v${SaveSystem.SCHEMA_VERSION}</div></div>
      </div>
      <div class="card saves-panel">
        <div class="menu-head"><div><h2 class="page-title">Career Saves</h2><div class="subtle">Four independent careers. Starting clubs are permanent per save.</div></div><span class="tag">LOCAL SAVES</span></div>
        <div class="save-grid">${slots.map(renderSaveSlot).join('')}</div>
      </div>
    </section>`);
  }
  function renderSaveSlot({index,career}){
    if(!career)return `<article class="card save-slot empty"><div class="slot-top"><span class="save-badge">SLOT ${index+1}</span><span class="muted">Empty</span></div><div><div class="slot-name">New story</div><div class="slot-meta">Create a player and discover where the career begins.</div></div><div class="slot-actions"><button class="btn btn-primary btn-small" data-action="new-career-slot" data-slot="${index}">Create Career</button></div></article>`;
    const p=career.player,club=CareerSystem.getClub(career),next=CareerSystem.nextFixture(career);
    return `<article class="card save-slot"><div class="slot-top"><span class="save-badge">SLOT ${index+1}</span><span class="tag accent">${U.escapeHTML(career.seasonLabel)}</span></div><div><div class="slot-name">${U.escapeHTML(p.firstName)} ${U.escapeHTML(p.surname)}</div><div class="slot-meta">${p.primaryPosition} · ${p.overall} OVR · ${U.escapeHTML(club?.name||'Unknown Club')}<br>${U.escapeHTML(career.squadLevel)} · ${next?`Next: ${U.formatDate(next.date,{day:'numeric',month:'short'})}`:'Season complete'}</div></div><div class="slot-actions"><button class="btn btn-primary btn-small" data-action="load-career" data-slot="${index}">Continue</button><button class="btn btn-ghost btn-small" data-action="delete-career" data-slot="${index}">Delete</button></div></article>`;
  }
  const field=(label,key,value,type='text',attrs='')=>`<div class="field"><label>${label}</label><input type="${type}" value="${U.escapeHTML(value)}" data-creator-field="${key}" ${attrs}></div>`;
  const selectField=(label,key,value,options)=>`<div class="field"><label>${label}</label><select data-creator-field="${key}">${options.map(o=>{const v=typeof o==='string'?o:o.value,n=typeof o==='string'?o:o.label;return `<option value="${U.escapeHTML(v)}" ${String(v)===String(value)?'selected':''}>${U.escapeHTML(n)}</option>`}).join('')}</select></div>`;
  function creatorSection(step,c){
    const countryOpts=FCData.countries.map(x=>({value:x.id,label:`${x.flag} ${x.name}`}));
    if(step===0)return `<div class="form-section"><h3>Identity</h3><div class="fields">
      ${field('First name','firstName',c.firstName)}${field('Surname','surname',c.surname)}${field('Nickname','nickname',c.nickname)}${field('Shirt name','shirtName',c.shirtName)}
      ${selectField('Nationality','nationality',c.nationality,countryOpts)}${field('Birthplace','birthplace',c.birthplace)}${field('Date of birth','dateOfBirth',c.dateOfBirth,'date')}${selectField('Starting age','startingAge',c.startingAge,[15,16,17,18])}${field('Preferred shirt #','shirtNumberPreference',c.shirtNumberPreference,'number','min="1" max="99"')}
    </div></div>`;
    if(step===1)return `<div class="form-section"><h3>Face</h3><div class="fields">
      ${selectField('Skin tone','appearance.skinTone',c.appearance.skinTone,['light','fair','tan','brown','deep','dark'])}${selectField('Face shape','appearance.faceShape',c.appearance.faceShape,['narrow','oval','round','square','diamond'])}
      ${selectField('Head shape','appearance.headShape',c.appearance.headShape,['normal','short','long'])}${selectField('Eyes','appearance.eyes',c.appearance.eyes,['standard','narrow','wide'])}${selectField('Eye colour','appearance.eyeColor',c.appearance.eyeColor,['brown','dark','hazel','green','blue','grey'])}${selectField('Eyebrows','appearance.eyebrows',c.appearance.eyebrows,['normal','thick','fine'])}
      ${selectField('Nose','appearance.nose',c.appearance.nose,['standard','narrow','wide'])}${selectField('Mouth','appearance.mouth',c.appearance.mouth,['neutral','smile','firm'])}${selectField('Jaw','appearance.jaw',c.appearance.jaw,['standard','soft','strong'])}${selectField('Ears','appearance.ears',c.appearance.ears,['standard','small','large'])}
    </div></div><div class="form-section"><h3>Hair & Details</h3><div class="fields">
      ${selectField('Hairstyle','appearance.hairstyle',c.appearance.hairstyle,['buzz','fade','curls','afro','braids','locs','long'])}${selectField('Hair length','appearance.hairLength',c.appearance.hairLength,['short','medium','long'])}${selectField('Hair colour','appearance.hairColor',c.appearance.hairColor,['black','darkBrown','brown','blonde','ginger','platinum'])}${selectField('Facial hair','appearance.facialHair',c.appearance.facialHair,['none','stubble','beard'])}${selectField('Facial hair colour','appearance.facialHairColor',c.appearance.facialHairColor,['black','darkBrown','brown','blonde','ginger'])}
      ${selectField('Freckles','appearance.freckles',c.appearance.freckles,['no','yes'])}${selectField('Scar','appearance.scar',c.appearance.scar,['none','left','right'])}${selectField('Facial detail','appearance.facialDetail',c.appearance.facialDetail,['none','cheek marks','under-eye'])}${selectField('Arm tattoos','appearance.armTattoo',c.appearance.armTattoo,['no','yes'])}${selectField('Leg tattoos','appearance.legTattoo',c.appearance.legTattoo,['no','yes'])}
    </div></div>`;
    if(step===2)return `<div class="form-section"><h3>Physical Build</h3><div class="fields">
      ${field('Height (cm)','height',c.height,'number','min="155" max="205"')}${field('Weight (kg)','weight',c.weight,'number','min="50" max="110"')}${selectField('Body build','bodyBuild',c.bodyBuild,['lean','athletic','stocky','strong'])}
    </div></div><div class="form-section"><h3>Kit Style</h3><div class="fields">
      ${selectField('Shirt','appearance.shirtTucked',c.appearance.shirtTucked,[{value:'untucked',label:'Untucked'},{value:'tucked',label:'Tucked'}])}${selectField('Sleeves','appearance.sleeveLength',c.appearance.sleeveLength,['short','long'])}${selectField('Sock height','appearance.sockHeight',c.appearance.sockHeight,['low','normal','high'])}${selectField('Boot style','appearance.bootStyle',c.appearance.bootStyle,['speed','control','classic'])}${selectField('Boot colour','appearance.bootColor',c.appearance.bootColor,['black','white','red','blue','green','gold'])}${selectField('Wrist tape','appearance.wristTape',c.appearance.wristTape,['no','yes'])}${selectField('Gloves','appearance.gloves',c.appearance.gloves,['no','yes'])}${selectField('Undershirt','appearance.undershirt',c.appearance.undershirt,['no','yes'])}
    </div></div>`;
    if(step===3)return `<div class="form-section"><h3>Football Profile</h3><div class="fields">
      ${selectField('Primary position','primaryPosition',c.primaryPosition,U.positions)}${selectField('Secondary position','secondaryPosition',c.secondaryPosition,U.positions)}${selectField('Preferred foot','preferredFoot',c.preferredFoot,['Right','Left'])}
      <div class="field full"><label>Starting ability</label><div class="card" style="padding:11px;background:rgba(55,226,154,.05)"><strong>Generated by the game</strong><div class="subtle" style="margin-top:4px">Position, age and build shape the profile, but you cannot allocate rating points. Overall and hidden potential are created only when the career begins.</div></div></div>
    </div></div>`;
    return `<div class="form-section"><h3>Final Preview</h3><div class="card" style="padding:12px;background:rgba(255,255,255,.035)"><div class="profile-topline"><div class="profile-name"><h2>${U.escapeHTML(c.firstName)} ${U.escapeHTML(c.surname)}</h2><p>${FCData.countries.find(x=>x.id===c.nationality)?.flag||''} ${U.escapeHTML(FCData.countries.find(x=>x.id===c.nationality)?.name||c.nationality)} · ${c.primaryPosition} / ${c.secondaryPosition} · ${c.preferredFoot} foot</p></div><span class="tag accent">AGE ${c.startingAge}</span></div><div class="preview-stat-row"><div class="preview-stat"><b>${c.height}</b><span>CM</span></div><div class="preview-stat"><b>${c.weight}</b><span>KG</span></div><div class="preview-stat"><b>${U.escapeHTML(c.bodyBuild)}</b><span>BUILD</span></div><div class="preview-stat"><b>#${c.shirtNumberPreference}</b><span>PREFERRED</span></div></div><div class="divider"></div><div class="subtle">When you press Begin Career, the game generates your starting attributes and hidden development profile, then permanently assigns a weighted-random starting club to this save. There is no club reroll.</div></div></div>`;
  }
  function renderCreator(c,step,slot){
    const labels=['Identity','Appearance','Build','Position','Preview'];
    const modelPlayer={...c,shirtNumber:c.shirtNumberPreference};
    set(`<section class="screen creator-screen">
      <div class="creator-top"><div><div class="card-title">NEW CAREER · SLOT ${slot+1}</div><h1 class="page-title">${labels[step]}</h1></div><div class="creator-progress">${labels.map((_,i)=>`<i class="creator-step-dot ${i<=step?'active':''}"></i>`).join('')}</div><button class="btn btn-ghost btn-small" data-action="cancel-creator">Cancel</button></div>
      <div class="creator-body"><div class="card preview-pane"><div class="preview-model"><div id="creator-model" class="player-model-wrap"></div></div><div class="preview-caption"><div><strong>${U.escapeHTML(c.shirtName||c.surname||'PLAYER')}</strong><div class="subtle">${c.primaryPosition} · ${c.preferredFoot} foot</div></div><span class="tag">LIVE MODEL</span></div></div><div class="card creator-form">${creatorSection(step,c)}</div></div>
      <div class="creator-foot"><button class="btn btn-secondary" data-action="creator-back" ${step===0?'disabled style="opacity:.35"':''}>← Back</button><div class="creator-summary">Appearance changes update the model instantly.</div>${step<4?'<button class="btn btn-primary" data-action="creator-next">Next →</button>':'<button class="btn btn-primary" data-action="begin-career">Begin Career ⚽</button>'}</div>
    </section>`);
    PlayerModel.mount(document.getElementById('creator-model'),modelPlayer,{kitColors:['#2585ba','#dff7ff']});
  }
  function renderReveal(career,revealed=false){
    const p=career.player,club=CareerSystem.getClub(career),country=FCData.countries.find(c=>c.id===club.country);
    set(`<section class="screen reveal-screen"><div class="card reveal-card"><div class="scanner"></div><div class="reveal-stage">${revealed?
      `<div class="reveal-kicker">YOUR CAREER BEGINS AT</div><div class="reveal-logo" style="background:linear-gradient(135deg,${club.colors[0]},${club.colors[1]});color:${club.colors[1]}">${U.escapeHTML(club.short)}</div><div class="reveal-club">${U.escapeHTML(club.name)}</div><div class="reveal-country">${country?.flag||''} ${U.escapeHTML(club.city)} · ${U.escapeHTML(club.league)}</div><div class="reveal-lines"><span>${p.primaryPosition}</span><span>AGE ${p.startingAge}</span><span>${p.overall} OVR</span><span>${U.escapeHTML(career.squadLevel)}</span></div><div class="reveal-actions"><button class="btn btn-primary" data-action="enter-career">Enter the Academy →</button></div>`:
      `<div class="reveal-kicker">CAREER GENERATION</div><div class="reveal-wait">Scouting report being processed…</div><div class="reveal-lines"><span>${FCData.countries.find(x=>x.id===p.nationality)?.flag||''} ${U.escapeHTML(FCData.countries.find(x=>x.id===p.nationality)?.name||'')}</span><span>${p.primaryPosition}</span><span>AGE ${p.startingAge}</span></div><p class="muted">Academy placement · recruitment network · ability profile · geography</p>`}</div></div></section>`);
  }
  function gameShell(career,section,content){
    const club=CareerSystem.getClub(career),p=career.player;
    set(`<section class="screen game-screen"><div class="game-view"><div class="game-page"><header class="game-header"><div class="header-left"><div class="club-chip">${clubLogo(club,'mini-club-logo')}<div><strong>${U.escapeHTML(club.name)}</strong><div class="subtle">${U.escapeHTML(career.squadLevel)} · ${p.overall} OVR</div></div></div></div><div class="header-actions"><span class="date-chip">${U.formatDate(career.currentDate)}</span><button class="btn btn-ghost btn-small" data-action="manual-save">Save</button></div></header><div style="min-height:0">${content}</div></div></div>${nav(section)}</section>`);
  }
  function nav(active){return `<nav class="bottom-nav">${[['home','⌂','HOME'],['player','◎','PLAYER'],['match','▶','MATCH'],['career','★','CAREER'],['world','◉','WORLD'],['more','•••','MORE']].map(([id,ic,tx])=>`<button class="nav-btn ${active===id?'active':''}" data-action="nav" data-section="${id}"><span>${ic}</span><span>${tx}</span></button>`).join('')}</nav>`}
  function renderHome(c){
    const club=CareerSystem.getClub(c),p=c.player,n=CareerSystem.nextFixture(c),last=[...c.fixtures].reverse().find(f=>f.played);
    const oppClub={short:(n?.opponent||'END').split(' ').map(x=>x[0]).join('').slice(0,3),colors:['#33485a','#cbd7df']};
    gameShell(c,'home',`<div class="dashboard-grid">
      <div class="card dashboard-player"><div class="preview-model"><div id="dashboard-model" class="player-model-wrap"></div></div><div class="player-id"><div><h2>${U.escapeHTML(p.firstName)} ${U.escapeHTML(p.surname)}</h2><div class="player-mini-meta">${p.primaryPosition} · #${p.shirtNumber}<br>${U.escapeHTML(c.managerRole)}</div></div><div class="ovr-badge"><div><b>${p.overall}</b><span>OVR</span></div></div></div></div>
      <div class="card next-match-card"><div class="card-title">${n?'NEXT MATCH':'SEASON COMPLETE'}</div>${n?`<div class="fixture-hero"><div class="fixture-teams"><div class="fixture-team">${n.home?clubLogo(club):`<div class="fixture-logo" style="background:#33485a">${U.escapeHTML(oppClub.short)}</div>`}<span>${U.escapeHTML(n.home?club.name:n.opponent)}</span></div><div class="vs">VS</div><div class="fixture-team">${!n.home?clubLogo(club):`<div class="fixture-logo" style="background:#33485a">${U.escapeHTML(oppClub.short)}</div>`}<span>${U.escapeHTML(!n.home?club.name:n.opponent)}</span></div></div><div class="fixture-info">${U.formatDate(n.date)} · ${U.escapeHTML(n.competition)}</div></div><div class="match-actions"><button class="btn btn-primary" data-action="quick-sim">Quick Sim</button><button class="btn btn-secondary" data-action="live-sim">Live Sim</button></div>`:`<div class="fixture-hero"><strong>All scheduled fixtures have been played.</strong><div class="muted">Your season statistics remain stored in this save.</div></div><button class="btn btn-secondary" data-action="nav" data-section="player">View season stats</button>`}</div>
      <div class="dashboard-side"><div class="card status-card"><div class="card-title">PLAYER STATUS</div><div class="status-grid"><div class="metric"><strong>${c.managerTrust}</strong><span>Manager trust</span></div><div class="metric"><strong>${p.form.toFixed(1)}</strong><span>Form</span></div><div class="metric"><strong>${p.fitness}%</strong><span>Fitness</span></div><div class="metric"><strong>${p.morale}%</strong><span>Morale</span></div></div></div><div class="card status-card"><div class="card-title">SEASON</div><div class="status-grid"><div class="metric"><strong>${c.seasonStats.appearances}</strong><span>Apps</span></div><div class="metric"><strong>${c.seasonStats.goals}</strong><span>Goals</span></div><div class="metric"><strong>${c.seasonStats.assists}</strong><span>Assists</span></div><div class="metric"><strong>${c.seasonStats.averageRating||'—'}</strong><span>Avg rating</span></div></div></div><div class="card feed-card"><div class="card-title">LATEST NEWS</div><div class="mini-feed">${c.news.slice(0,4).map(x=>`<div class="feed-item"><strong>${U.escapeHTML(x.title)}</strong><time>${U.formatDate(x.date,{day:'numeric',month:'short'})}</time></div>`).join('')}</div></div></div>
    </div>`);
    PlayerModel.mount(document.getElementById('dashboard-model'),p,{kitColors:club.colors});
  }
  function attrCards(c){
    const a=c.player.attributes,group=U.positionGroups[c.player.primaryPosition];
    const groups=Object.entries(U.attributeGroups).filter(([name])=>name!=='Goalkeeping'||group==='GK').filter(([name])=>!(group==='GK'&&['Shooting','Control'].includes(name)));
    return groups.map(([name,keys])=>`<div class="attribute-card"><h4>${name}</h4>${keys.map(k=>`<div class="attr-row"><span>${U.escapeHTML(U.attributeLabels[k])}</span><b>${a[k]}</b></div>`).join('')}</div>`).join('');
  }
  function renderPlayer(c){
    const p=c.player,club=CareerSystem.getClub(c),s=c.seasonStats,country=FCData.countries.find(x=>x.id===p.nationality);
    gameShell(c,'player',`<div class="profile-grid"><div class="card profile-left"><div class="preview-model"><div id="profile-model" class="player-model-wrap"></div></div><div><div class="player-id"><div><h2>${U.escapeHTML(p.firstName)} ${U.escapeHTML(p.surname)}</h2><div class="player-mini-meta">${country?.flag||''} ${U.escapeHTML(country?.name||'')} · ${p.primaryPosition}/${p.secondaryPosition}<br>${p.height} cm · ${p.weight} kg · ${p.preferredFoot} foot</div></div><div class="ovr-badge"><div><b>${p.overall}</b><span>OVR</span></div></div></div></div></div><div class="card profile-right"><div class="profile-topline"><div class="profile-name"><h2>Player Profile</h2><p>${U.escapeHTML(club.name)} · ${U.escapeHTML(c.squadLevel)} · ${U.escapeHTML(c.managerRole)}</p></div><div><span class="tag">${U.formatMoney(p.marketValue)} value</span> <span class="tag accent">${p.reputation.toFixed(0)} REP</span></div></div><div class="preview-stat-row"><div class="preview-stat"><b>${s.appearances}</b><span>APPS</span></div><div class="preview-stat"><b>${s.goals}</b><span>GOALS</span></div><div class="preview-stat"><b>${s.assists}</b><span>ASSISTS</span></div><div class="preview-stat"><b>${s.averageRating||'—'}</b><span>AVG RATING</span></div></div><div class="attribute-groups">${attrCards(c)}</div><div class="attribute-card" style="margin-top:8px"><h4>TECHNIQUE</h4><div class="attr-row"><span>Weak Foot</span><b>${'★'.repeat(p.attributes.weakFoot)}${'☆'.repeat(5-p.attributes.weakFoot)}</b></div><div class="attr-row"><span>Skill Ability</span><b>${'★'.repeat(p.attributes.skillAbility)}${'☆'.repeat(5-p.attributes.skillAbility)}</b></div></div></div></div>`);
    PlayerModel.mount(document.getElementById('profile-model'),p,{kitColors:club.colors});
  }
  function renderMatch(c){
    const n=CareerSystem.nextFixture(c),club=CareerSystem.getClub(c);
    gameShell(c,'match',`<div class="match-page"><div class="card match-preview"><div class="card-title">MATCHDAY PLAYER</div><div class="lineup-player"><div id="match-model" class="player-model-wrap"></div></div><div class="player-id"><div><strong>${U.escapeHTML(c.player.shirtName)}</strong><div class="subtle">${c.player.primaryPosition} · Fitness ${c.player.fitness}%</div></div><span class="tag accent">FORM ${c.player.form.toFixed(1)}</span></div></div><div class="card match-panel">${n?`<h3>${U.escapeHTML(club.name)} vs ${U.escapeHTML(n.opponent)}</h3><div class="subtle">${U.formatDate(n.date)} · ${U.escapeHTML(n.competition)} · ${n.home?'Home':'Away'}</div><div class="divider"></div><div class="match-mode-grid"><div class="mode-card"><h4>Quick Sim</h4><p>Immediately calculate the full match and your individual performance.</p><button class="btn btn-primary btn-small" data-action="quick-sim">Sim Match</button></div><div class="mode-card"><h4>Live Sim</h4><p>Watch a lightweight commentary feed unfold before the post-match report.</p><button class="btn btn-secondary btn-small" data-action="live-sim">Watch Live</button></div></div><div class="divider"></div><div class="card-title">CURRENT STATUS</div><div class="statline"><span>Manager role</span><b>${U.escapeHTML(c.managerRole)}</b></div><div class="statline"><span>Manager trust</span><b>${c.managerTrust}/100</b></div><div class="statline"><span>Fitness</span><b>${c.player.fitness}%</b></div><div class="statline"><span>Morale</span><b>${c.player.morale}%</b></div>`:`<h3>Season complete</h3><p class="muted">No unplayed fixtures remain in this first-build schedule.</p>`}</div></div>`);
    PlayerModel.mount(document.getElementById('match-model'),c.player,{kitColors:club.colors});
  }
  function renderCareer(c){
    const club=CareerSystem.getClub(c);
    gameShell(c,'career',`<div class="calendar-layout"><div class="card season-summary"><div class="card-title">CLUB STATUS</div><h2 style="margin:5px 0">${U.escapeHTML(club.name)}</h2><div class="subtle">${U.escapeHTML(club.city)} · ${U.escapeHTML(club.league)}</div><div class="divider"></div><div class="statline"><span>Squad</span><b>${U.escapeHTML(c.squadLevel)}</b></div><div class="statline"><span>Role</span><b>${U.escapeHTML(c.managerRole)}</b></div><div class="statline"><span>Manager trust</span><b>${c.managerTrust}</b></div><div class="statline"><span>Contract</span><b>${U.escapeHTML(c.contract.type)}</b></div><div class="statline"><span>Wage</span><b>${U.formatMoney(c.contract.wage)}/wk</b></div><div class="statline"><span>Contract ends</span><b>${U.formatDate(c.contract.endDate)}</b></div></div><div class="card fixtures-card"><div class="card-title">CAREER TIMELINE</div>${c.timeline.map(x=>`<div class="timeline-item"><div class="timeline-year">${x.date.slice(0,4)}</div><div class="timeline-text"><strong>${U.escapeHTML(x.title)}</strong><div class="muted">${U.escapeHTML(x.detail||'')} · ${U.formatDate(x.date,{day:'numeric',month:'short'})}</div></div></div>`).join('')}</div></div>`);
  }
  function renderWorld(c){
    const club=CareerSystem.getClub(c),played=c.fixtures.filter(f=>f.played),upcoming=c.fixtures.filter(f=>!f.played);
    gameShell(c,'world',`<div class="calendar-layout"><div class="card season-summary"><div class="card-title">SEASON SNAPSHOT</div><div class="big-stat">${played.length}<span class="muted" style="font-size:15px">/${c.fixtures.length}</span></div><div class="subtle">Fixtures played</div><div class="season-summary-grid"><div class="preview-stat"><b>${c.seasonStats.goals}</b><span>GOALS</span></div><div class="preview-stat"><b>${c.seasonStats.assists}</b><span>ASSISTS</span></div><div class="preview-stat"><b>${c.seasonStats.potm}</b><span>8.5+ GAMES</span></div><div class="preview-stat"><b>${upcoming.length}</b><span>REMAINING</span></div></div><div class="divider"></div><div class="card-title">CLUB WORLD</div><p class="subtle">This first build simulates your career schedule and match world. Full league tables, transfers and other-league simulation are planned for later stages.</p></div><div class="card fixtures-card"><div class="card-title">FIXTURES · ${U.escapeHTML(club.league)}</div>${c.fixtures.map(f=>`<div class="fixture-row ${f.played?'played':''} ${CareerSystem.nextFixture(c)?.id===f.id?'current':''}"><span class="fixture-date">${U.formatDate(f.date,{day:'numeric',month:'short'})}</span><span class="fixture-opponent">${f.home?'vs':'@'} ${U.escapeHTML(f.opponent)}</span><span class="fixture-result">${f.played?`${f.result.homeGoals}-${f.result.awayGoals}`:'—'}</span><span class="subtle">${f.played&&f.playerStats?.minutes?`${f.playerStats.rating.toFixed(1)} rating`:f.played?'DNP':'Upcoming'}</span></div>`).join('')}</div></div>`);
  }
  function renderMore(c){
    gameShell(c,'more',`<div class="more-grid"><div class="card more-card"><h3>Save Career</h3><p>Your career autosaves after every match. You can also save it immediately.</p><button class="btn btn-primary btn-small" data-action="manual-save">Save now</button></div><div class="card more-card"><h3>Main Menu</h3><p>Return to your save slots. Your current career remains stored.</p><button class="btn btn-secondary btn-small" data-action="return-menu">Main menu</button></div><div class="card more-card"><h3>Reduced Motion</h3><p>Use shorter animations for reveal and live commentary.</p><button class="btn btn-ghost btn-small" data-action="toggle-motion">${c.settings.reducedMotion?'Turn off':'Turn on'}</button></div><div class="card more-card"><h3>Career ID</h3><p>${U.escapeHTML(c.meta.id)}</p><span class="tag">SAVE FORMAT v${c.meta.schemaVersion}</span></div><div class="card more-card"><h3>Starting Club</h3><p>${U.escapeHTML(CareerSystem.getClub(c).name)} was assigned during career generation and cannot be rerolled.</p><span class="tag accent">PERMANENT</span></div><div class="card more-card"><h3>Help</h3><p>Use Match for simulations, Player for attributes and stats, Career for club status, and World for your fixture calendar.</p></div></div>`);
  }
  function renderSection(c,section){({home:renderHome,player:renderPlayer,match:renderMatch,career:renderCareer,world:renderWorld,more:renderMore}[section]||renderHome)(c)}
  function matchReport(c,result){
    const s=result.stats,n=c.fixtures.find(f=>f.id===result.fixtureId),score=`${result.teamGoals}–${result.oppGoals}`;
    const body=`<div class="profile-topline"><div><div class="card-title">FULL TIME</div><h2 style="margin:4px 0">${score}</h2><div class="subtle">vs ${U.escapeHTML(n?.opponent||'Opponent')}</div></div><div class="ovr-badge"><div><b>${s.minutes?s.rating.toFixed(1):'—'}</b><span>RATING</span></div></div></div><div class="preview-stat-row"><div class="preview-stat"><b>${s.minutes}</b><span>MINUTES</span></div><div class="preview-stat"><b>${s.goals}</b><span>GOALS</span></div><div class="preview-stat"><b>${s.assists}</b><span>ASSISTS</span></div><div class="preview-stat"><b>${s.started?'XI':s.minutes?'SUB':'DNP'}</b><span>ROLE</span></div></div><div class="divider"></div><div class="attribute-groups"><div class="attribute-card"><h4>ATTACK</h4><div class="attr-row"><span>Shots</span><b>${s.shots}</b></div><div class="attr-row"><span>On target</span><b>${s.shotsOnTarget}</b></div><div class="attr-row"><span>Dribbles</span><b>${s.dribbles}</b></div><div class="attr-row"><span>Key passes</span><b>${s.keyPasses}</b></div></div><div class="attribute-card"><h4>PASSING</h4><div class="attr-row"><span>Passes</span><b>${s.passesCompleted}/${s.passes}</b></div><div class="attr-row"><span>Accuracy</span><b>${s.passes?Math.round(s.passesCompleted/s.passes*100):0}%</b></div><div class="attr-row"><span>Possession lost</span><b>${s.possessionLost}</b></div><div class="attr-row"><span>Distance</span><b>${s.distanceKm} km</b></div></div><div class="attribute-card"><h4>DEFENCE</h4><div class="attr-row"><span>Tackles</span><b>${s.tackles}</b></div><div class="attr-row"><span>Interceptions</span><b>${s.interceptions}</b></div><div class="attr-row"><span>Clearances</span><b>${s.clearances}</b></div><div class="attr-row"><span>Saves</span><b>${s.saves}</b></div></div></div>`;
    openModal({title:'Post-Match Report',body,footer:'<span class="subtle">Performance updates your form and manager trust.</span><button class="btn btn-primary" data-action="finish-match">Continue</button>',closable:false});
  }
  return {toast,openModal,closeModal,renderMenu,renderCreator,renderReveal,renderSection,matchReport};
})();
